### ISSUE TITLE
Enemy and bullet rendering improvement

### ISSUE THREAD

**Issue by myxo** [myxo/ascii_doom#44]
Сейчас для рендеринга пуль и мобов используется ray tracing, что крайне излишне, так как для этих объектов нам не нужно делать рендеринг с учетом перспективы. Дистанция может находится напрямую по формуле расстояния между двумя точками. Чтобы понять экранные координаты x, можно сопоставить угол до объекта и view angle игрока

**Comment by yarkivaev** [comment]
@myxo , у меня не получается обойтись без ray tracing, так как когда враг стоит за углом и его центр виден игроку, то та часть, которая должна быть скрыта, рендерится поверх стены.

**Comment by yarkivaev** [comment]
В коммите [78fe634](https://github.com/myxo/ascii_doom/commit/78fe634a4725c3b786dbfff03c4b68a20b955058) я попытался делать ray tracing только для того участка, где находится враг, но это ещё менее эффективно чем ray tracing по всей области видимости.

**Comment by myxo** [comment]
"та часть, которая должна быть скрыта, рендерится поверх стены" - это должно будет решаться другим способом (depth buffer), который будет потом

**Comment by myxo** [comment]
btw. У нас сейчас из-за этого серьезная просадка в производительности. 20-30 FPS. Больше 70% времени программа проводит в функции is_enemy
![2020-07-16_03-18-25](https://user-images.githubusercontent.com/2719353/87612563-923d0500-c713-11ea-82b8-330785c9ac5a.png)
