### ISSUE TITLE
Watch variables

### ISSUE THREAD

**Issue by myxo** [myxo/ascii_doom#5]
В ходе отладки иногда необходимо следить на значениями определенных переменных. Но в нашем случае сделать это через stdout не представляется возможным. Нужно чтобы такие переменные выводились на экран.
```
void add_watch(const char* var_name, double value);
void stop_watch(const char* var_name);
void display_watch();
```
Внутри logging.c должна лежать табличка (можно сделать массивом) в которую добавляются / обновляются переменные через `add_watch`. Соответственно через `stop_watch` эти переменные удаляются. `display_watch` должна отображать на экран (посмотри где удобнее, если что потом переместим) в формате
```
var_name_1 : value1
var_name_2: value1
```
С клиентской стороны ожидается, что тот, кто захочет логировать, будет вызывать при каждом `update` `add_watch`. 

Зависит от #1

**Comment by TheBlek** [comment]
У меня есть вполне работающий вариант, но не в отдельном файле. Если нужно будет, идите в мою ветку
